# Deployment da API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  labels:
    app: users-api
    app.kubernetes.io/name: users-api
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: fiap-users-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: users-api-config
            - secretRef:
                name: users-api-secrets

---
# Deployment do SQL Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  labels:
    app.kubernetes.io/name: sqlserver
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
        app.kubernetes.io/name: sqlserver
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
              name: sqlserver
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secrets
                  key: MSSQL_SA_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: sqlserver-data
              mountPath: /var/opt/mssql
      volumes:
        - name: sqlserver-data
          persistentVolumeClaim:
            claimName: sqlserver-data
