# Secrets para a API
apiVersion: v1
kind: Secret
metadata:
  name: users-api-secrets
  labels:
    app.kubernetes.io/name: users-api
    app.kubernetes.io/component: api
type: Opaque
stringData:
  # IMPORTANTE: Substitua esses valores em produção!
  # Use um gerenciador de secrets
  ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=FiapCloudGamesDb;User Id=SA;Password=Mysql2022!;TrustServerCertificate=True"
  Jwt__Key: "minha-chave-jwt-super-secreta-2026-api-segura"
  Jwt__Issuer: "FiapCloudGames"
  Jwt__Audience: "FiapCloudGames"

---
# Secrets para o SQL Server
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secrets
  labels:
    app.kubernetes.io/name: sqlserver
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "Mysql2022!"
