apiVersion: v1
kind: Secret
metadata:
  name: users-api-secrets
  labels:
    app.kubernetes.io/name: users-api
    app.kubernetes.io/component: api
type: Opaque
stringData:
  # IMPORTANTE: Substitua esses valores em produção!
  # Use um gerenciador de secrets
  ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=FiapCloudGames;User Id=sa;Password=YOUR_PASSWORD;TrustServerCertificate=True"
  Jwt__Key: "YOUR_SUPER_SECRET_JWT_KEY_MIN_32_CHARS"
  Jwt__Issuer: "FiapCloudGames"
  Jwt__Audience: "FiapCloudGames"
