# Service para a API
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: fiap-cloud-games
  labels:
    app.kubernetes.io/name: users-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: fiap-cloud-games
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: users-api

---
# Service para o SQL Server
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: fiap-cloud-games
  labels:
    app.kubernetes.io/name: sqlserver
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: fiap-cloud-games
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
      name: sqlserver
  selector:
    app: sqlserver
