// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FiapCloudGames.Users.BDD.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CadastroDeUsuarioFeature : object, Xunit.IClassFixture<CadastroDeUsuarioFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Cadastro de Usuário", "    Como um novo usuário\r\n    Eu quero me cadastrar na plataforma\r\n    Para que e" +
                "u possa acessar o sistema e utilizar seus recursos", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CadastroUsuario.feature"
#line hidden
        
        public CadastroDeUsuarioFeature(CadastroDeUsuarioFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
#line hidden
#line 8
    await testRunner.GivenAsync("que não existe nenhum usuário cadastrado com o email \"novo@email.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário com dados válidos")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuário")]
        [Xunit.TraitAttribute("Description", "Cadastro de usuário com dados válidos")]
        public async System.Threading.Tasks.Task CadastroDeUsuarioComDadosValidos()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário com dados válidos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table1.AddRow(new string[] {
                            "Maria Silva",
                            "novo@email.com",
                            "Senha@123"});
#line 11
    await testRunner.WhenAsync("eu tento cadastrar um usuário com os seguintes dados:", ((string)(null)), table1, "Quando ");
#line hidden
#line 14
    await testRunner.ThenAsync("o cadastro deve ser bem-sucedido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 15
    await testRunner.AndAsync("o ID do usuário deve ser retornado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 16
    await testRunner.AndAsync("o usuário deve ser adicionado ao repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastro com senha sem letra maiúscula")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuário")]
        [Xunit.TraitAttribute("Description", "Cadastro com senha sem letra maiúscula")]
        public async System.Threading.Tasks.Task CadastroComSenhaSemLetraMaiuscula()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro com senha sem letra maiúscula", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table2.AddRow(new string[] {
                            "João Santos",
                            "novo@email.com",
                            "senha@123"});
#line 19
    await testRunner.WhenAsync("eu tento cadastrar um usuário com os seguintes dados:", ((string)(null)), table2, "Quando ");
#line hidden
#line 22
    await testRunner.ThenAsync("o cadastro deve falhar com erro \"A senha deve conter ao menos uma letra maiúscula" +
                        ".\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 23
    await testRunner.AndAsync("nenhum usuário deve ser adicionado ao repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastro com senha sem letra minúscula")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuário")]
        [Xunit.TraitAttribute("Description", "Cadastro com senha sem letra minúscula")]
        public async System.Threading.Tasks.Task CadastroComSenhaSemLetraMinuscula()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro com senha sem letra minúscula", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table3.AddRow(new string[] {
                            "João Santos",
                            "novo@email.com",
                            "SENHA@123"});
#line 26
    await testRunner.WhenAsync("eu tento cadastrar um usuário com os seguintes dados:", ((string)(null)), table3, "Quando ");
#line hidden
#line 29
    await testRunner.ThenAsync("o cadastro deve falhar com erro \"A senha deve conter ao menos uma letra minúscula" +
                        ".\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 30
    await testRunner.AndAsync("nenhum usuário deve ser adicionado ao repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastro com senha sem número")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuário")]
        [Xunit.TraitAttribute("Description", "Cadastro com senha sem número")]
        public async System.Threading.Tasks.Task CadastroComSenhaSemNumero()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro com senha sem número", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table4.AddRow(new string[] {
                            "João Santos",
                            "novo@email.com",
                            "Senha@abc"});
#line 33
    await testRunner.WhenAsync("eu tento cadastrar um usuário com os seguintes dados:", ((string)(null)), table4, "Quando ");
#line hidden
#line 36
    await testRunner.ThenAsync("o cadastro deve falhar com erro \"A senha deve conter ao menos um número.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 37
    await testRunner.AndAsync("nenhum usuário deve ser adicionado ao repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastro com senha sem caractere especial")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuário")]
        [Xunit.TraitAttribute("Description", "Cadastro com senha sem caractere especial")]
        public async System.Threading.Tasks.Task CadastroComSenhaSemCaractereEspecial()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro com senha sem caractere especial", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table5.AddRow(new string[] {
                            "João Santos",
                            "novo@email.com",
                            "Senha123"});
#line 40
    await testRunner.WhenAsync("eu tento cadastrar um usuário com os seguintes dados:", ((string)(null)), table5, "Quando ");
#line hidden
#line 43
    await testRunner.ThenAsync("o cadastro deve falhar com erro \"A senha deve conter ao menos um caractere especi" +
                        "al.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 44
    await testRunner.AndAsync("nenhum usuário deve ser adicionado ao repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastro com senha muito curta")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuário")]
        [Xunit.TraitAttribute("Description", "Cadastro com senha muito curta")]
        public async System.Threading.Tasks.Task CadastroComSenhaMuitoCurta()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro com senha muito curta", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table6.AddRow(new string[] {
                            "João Santos",
                            "novo@email.com",
                            "Ab1@"});
#line 47
    await testRunner.WhenAsync("eu tento cadastrar um usuário com os seguintes dados:", ((string)(null)), table6, "Quando ");
#line hidden
#line 50
    await testRunner.ThenAsync("o cadastro deve falhar com erro \"A senha deve ter no mínimo 8 caracteres.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 51
    await testRunner.AndAsync("nenhum usuário deve ser adicionado ao repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastro com email já existente")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuário")]
        [Xunit.TraitAttribute("Description", "Cadastro com email já existente")]
        public async System.Threading.Tasks.Task CadastroComEmailJaExistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro com email já existente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 54
    await testRunner.GivenAsync("que já existe um usuário cadastrado com o email \"existente@email.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table7.AddRow(new string[] {
                            "Pedro Lima",
                            "existente@email.com",
                            "Senha@123"});
#line 55
    await testRunner.WhenAsync("eu tento cadastrar um usuário com os seguintes dados:", ((string)(null)), table7, "Quando ");
#line hidden
#line 58
    await testRunner.ThenAsync("o cadastro deve falhar com erro \"Email já cadastrado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 59
    await testRunner.AndAsync("nenhum usuário deve ser adicionado ao repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastro com senha vazia")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuário")]
        [Xunit.TraitAttribute("Description", "Cadastro com senha vazia")]
        public async System.Threading.Tasks.Task CadastroComSenhaVazia()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro com senha vazia", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table8.AddRow(new string[] {
                            "Carlos Souza",
                            "novo@email.com",
                            ""});
#line 62
    await testRunner.WhenAsync("eu tento cadastrar um usuário com os seguintes dados:", ((string)(null)), table8, "Quando ");
#line hidden
#line 65
    await testRunner.ThenAsync("o cadastro deve falhar com erro \"Senha é obrigatória.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 66
    await testRunner.AndAsync("nenhum usuário deve ser adicionado ao repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Validação de regras de senha")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuário")]
        [Xunit.TraitAttribute("Description", "Validação de regras de senha")]
        [Xunit.InlineDataAttribute("abc123", "A senha deve ter no mínimo 8 caracteres.", new string[0])]
        [Xunit.InlineDataAttribute("ABCDEFGH1!", "A senha deve conter ao menos uma letra minúscula.", new string[0])]
        [Xunit.InlineDataAttribute("abcdefgh1!", "A senha deve conter ao menos uma letra maiúscula.", new string[0])]
        [Xunit.InlineDataAttribute("Abcdefgh!", "A senha deve conter ao menos um número.", new string[0])]
        [Xunit.InlineDataAttribute("Abcdefgh1", "A senha deve conter ao menos um caractere especial.", new string[0])]
        public async System.Threading.Tasks.Task ValidacaoDeRegrasDeSenha(string senha, string mensagem_Erro, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("senha", senha);
            argumentsOfScenario.Add("mensagem_erro", mensagem_Erro);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validação de regras de senha", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table9.AddRow(new string[] {
                            "Teste User",
                            "novo@email.com",
                            string.Format("{0}", senha)});
#line 69
    await testRunner.WhenAsync("eu tento cadastrar um usuário com os seguintes dados:", ((string)(null)), table9, "Quando ");
#line hidden
#line 72
    await testRunner.ThenAsync(string.Format("o cadastro deve falhar com erro \"{0}\"", mensagem_Erro), ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 73
    await testRunner.AndAsync("nenhum usuário deve ser adicionado ao repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verificar que usuário é criado com perfil Comum por padrão")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuário")]
        [Xunit.TraitAttribute("Description", "Verificar que usuário é criado com perfil Comum por padrão")]
        public async System.Threading.Tasks.Task VerificarQueUsuarioECriadoComPerfilComumPorPadrao()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verificar que usuário é criado com perfil Comum por padrão", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 83
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table10.AddRow(new string[] {
                            "Novo Usuario",
                            "novo@email.com",
                            "Senha@123"});
#line 84
    await testRunner.WhenAsync("eu tento cadastrar um usuário com os seguintes dados:", ((string)(null)), table10, "Quando ");
#line hidden
#line 87
    await testRunner.ThenAsync("o cadastro deve ser bem-sucedido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 88
    await testRunner.AndAsync("o usuário criado deve ter o perfil \"Comum\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verificar que a senha é armazenada como hash")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuário")]
        [Xunit.TraitAttribute("Description", "Verificar que a senha é armazenada como hash")]
        public async System.Threading.Tasks.Task VerificarQueASenhaEArmazenadaComoHash()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verificar que a senha é armazenada como hash", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 90
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table11.AddRow(new string[] {
                            "Usuario Hash",
                            "novo@email.com",
                            "Senha@123"});
#line 91
    await testRunner.WhenAsync("eu tento cadastrar um usuário com os seguintes dados:", ((string)(null)), table11, "Quando ");
#line hidden
#line 94
    await testRunner.ThenAsync("o cadastro deve ser bem-sucedido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 95
    await testRunner.AndAsync("a senha deve estar armazenada como hash BCrypt", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 96
    await testRunner.AndAsync("a senha em texto plano não deve estar armazenada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CadastroDeUsuarioFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CadastroDeUsuarioFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
