// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FiapCloudGames.Users.BDD.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PromoverUsuarioAAdministradorFeature : object, Xunit.IClassFixture<PromoverUsuarioAAdministradorFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Promover Usuário a Administrador", "    Como um administrador do sistema\r\n    Eu quero promover usuários comuns a adm" +
                "inistradores\r\n    Para que eles possam gerenciar o sistema", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TornarAdmin.feature"
#line hidden
        
        public PromoverUsuarioAAdministradorFeature(PromoverUsuarioAAdministradorFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
#line hidden
#line 8
    await testRunner.GivenAsync("que estou autenticado como administrador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Promover usuário comum a administrador com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Promover Usuário a Administrador")]
        [Xunit.TraitAttribute("Description", "Promover usuário comum a administrador com sucesso")]
        public async System.Threading.Tasks.Task PromoverUsuarioComumAAdministradorComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Promover usuário comum a administrador com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Tipo"});
                table13.AddRow(new string[] {
                            "João Silva",
                            "joao@email.com",
                            "Comum"});
#line 11
    await testRunner.GivenAsync("que existe um usuário comum com os seguintes dados:", ((string)(null)), table13, "Dado ");
#line hidden
#line 14
    await testRunner.WhenAsync("eu tento promover o usuário a administrador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 15
    await testRunner.ThenAsync("a promoção deve ser bem-sucedida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 16
    await testRunner.AndAsync("o usuário deve ter o perfil \"Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 17
    await testRunner.AndAsync("o usuário deve ser atualizado no repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Tentar promover usuário que não existe")]
        [Xunit.TraitAttribute("FeatureTitle", "Promover Usuário a Administrador")]
        [Xunit.TraitAttribute("Description", "Tentar promover usuário que não existe")]
        public async System.Threading.Tasks.Task TentarPromoverUsuarioQueNaoExiste()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tentar promover usuário que não existe", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 20
    await testRunner.GivenAsync("que não existe nenhum usuário com o ID \"00000000-0000-0000-0000-000000000000\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 21
    await testRunner.WhenAsync("eu tento promover o usuário com ID \"00000000-0000-0000-0000-000000000000\" a admin" +
                        "istrador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 22
    await testRunner.ThenAsync("a promoção deve falhar com erro \"Usuário não encontrado.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 23
    await testRunner.AndAsync("nenhum usuário deve ser atualizado no repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Promover usuário que já é administrador")]
        [Xunit.TraitAttribute("FeatureTitle", "Promover Usuário a Administrador")]
        [Xunit.TraitAttribute("Description", "Promover usuário que já é administrador")]
        public async System.Threading.Tasks.Task PromoverUsuarioQueJaEAdministrador()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Promover usuário que já é administrador", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Tipo"});
                table14.AddRow(new string[] {
                            "Maria Admin",
                            "maria@email.com",
                            "Admin"});
#line 26
    await testRunner.GivenAsync("que existe um usuário administrador com os seguintes dados:", ((string)(null)), table14, "Dado ");
#line hidden
#line 29
    await testRunner.WhenAsync("eu tento promover o usuário a administrador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 30
    await testRunner.ThenAsync("a promoção deve ser bem-sucedida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 31
    await testRunner.AndAsync("o usuário deve continuar com o perfil \"Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 32
    await testRunner.AndAsync("o usuário deve ser atualizado no repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verificar que o repositório é chamado apenas uma vez")]
        [Xunit.TraitAttribute("FeatureTitle", "Promover Usuário a Administrador")]
        [Xunit.TraitAttribute("Description", "Verificar que o repositório é chamado apenas uma vez")]
        public async System.Threading.Tasks.Task VerificarQueORepositorioEChamadoApenasUmaVez()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verificar que o repositório é chamado apenas uma vez", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Tipo"});
                table15.AddRow(new string[] {
                            "Carlos Lima",
                            "carlos@email.com",
                            "Comum"});
#line 35
    await testRunner.GivenAsync("que existe um usuário comum com os seguintes dados:", ((string)(null)), table15, "Dado ");
#line hidden
#line 38
    await testRunner.WhenAsync("eu tento promover o usuário a administrador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 39
    await testRunner.ThenAsync("a promoção deve ser bem-sucedida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 40
    await testRunner.AndAsync("o método de atualização do repositório deve ser chamado exatamente uma vez", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Promover múltiplos usuários em sequência")]
        [Xunit.TraitAttribute("FeatureTitle", "Promover Usuário a Administrador")]
        [Xunit.TraitAttribute("Description", "Promover múltiplos usuários em sequência")]
        public async System.Threading.Tasks.Task PromoverMultiplosUsuariosEmSequencia()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Promover múltiplos usuários em sequência", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Tipo"});
                table16.AddRow(new string[] {
                            "Pedro Santos",
                            "pedro@email.com",
                            "Comum"});
                table16.AddRow(new string[] {
                            "Ana Costa",
                            "ana@email.com",
                            "Comum"});
                table16.AddRow(new string[] {
                            "Lucas Souza",
                            "lucas@email.com",
                            "Comum"});
#line 43
    await testRunner.GivenAsync("que existem os seguintes usuários:", ((string)(null)), table16, "Dado ");
#line hidden
#line 48
    await testRunner.WhenAsync("eu promovo todos os usuários a administradores", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 49
    await testRunner.ThenAsync("todas as promoções devem ser bem-sucedidas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 50
    await testRunner.AndAsync("todos os usuários devem ter o perfil \"Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verificar que apenas o tipo de usuário é alterado")]
        [Xunit.TraitAttribute("FeatureTitle", "Promover Usuário a Administrador")]
        [Xunit.TraitAttribute("Description", "Verificar que apenas o tipo de usuário é alterado")]
        public async System.Threading.Tasks.Task VerificarQueApenasOTipoDeUsuarioEAlterado()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verificar que apenas o tipo de usuário é alterado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Tipo"});
                table17.AddRow(new string[] {
                            "Roberto Dias",
                            "roberto@email.com",
                            "Comum"});
#line 53
    await testRunner.GivenAsync("que existe um usuário comum com os seguintes dados:", ((string)(null)), table17, "Dado ");
#line hidden
#line 56
    await testRunner.WhenAsync("eu tento promover o usuário a administrador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 57
    await testRunner.ThenAsync("a promoção deve ser bem-sucedida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 58
    await testRunner.AndAsync("o nome do usuário não deve ser alterado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 59
    await testRunner.AndAsync("o email do usuário não deve ser alterado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 60
    await testRunner.AndAsync("apenas o tipo deve ser alterado para \"Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Tentar promover usuários com IDs inválidos")]
        [Xunit.TraitAttribute("FeatureTitle", "Promover Usuário a Administrador")]
        [Xunit.TraitAttribute("Description", "Tentar promover usuários com IDs inválidos")]
        [Xunit.InlineDataAttribute("00000000-0000-0000-0000-000000000000", new string[0])]
        [Xunit.InlineDataAttribute("ffffffff-ffff-ffff-ffff-ffffffffffff", new string[0])]
        [Xunit.InlineDataAttribute("12345678-1234-1234-1234-123456789012", new string[0])]
        public async System.Threading.Tasks.Task TentarPromoverUsuariosComIDsInvalidos(string usuarioId, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("usuarioId", usuarioId);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tentar promover usuários com IDs inválidos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 63
    await testRunner.WhenAsync(string.Format("eu tento promover o usuário com ID \"{0}\" a administrador", usuarioId), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 64
    await testRunner.ThenAsync("a promoção deve falhar com erro \"Usuário não encontrado.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 65
    await testRunner.AndAsync("nenhum usuário deve ser atualizado no repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verificar tratamento de erro ao atualizar repositório")]
        [Xunit.TraitAttribute("FeatureTitle", "Promover Usuário a Administrador")]
        [Xunit.TraitAttribute("Description", "Verificar tratamento de erro ao atualizar repositório")]
        public async System.Threading.Tasks.Task VerificarTratamentoDeErroAoAtualizarRepositorio()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verificar tratamento de erro ao atualizar repositório", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 73
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Tipo"});
                table18.AddRow(new string[] {
                            "Erro User",
                            "erro@email.com",
                            "Comum"});
#line 74
    await testRunner.GivenAsync("que existe um usuário comum com os seguintes dados:", ((string)(null)), table18, "Dado ");
#line hidden
#line 77
    await testRunner.AndAsync("que o repositório irá falhar ao atualizar", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 78
    await testRunner.WhenAsync("eu tento promover o usuário a administrador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 79
    await testRunner.ThenAsync("a promoção deve falhar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 80
    await testRunner.AndAsync("uma exceção deve ser lançada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Promover usuário e verificar persistência das alterações")]
        [Xunit.TraitAttribute("FeatureTitle", "Promover Usuário a Administrador")]
        [Xunit.TraitAttribute("Description", "Promover usuário e verificar persistência das alterações")]
        public async System.Threading.Tasks.Task PromoverUsuarioEVerificarPersistenciaDasAlteracoes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Promover usuário e verificar persistência das alterações", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Tipo"});
                table19.AddRow(new string[] {
                            "Usuario Teste",
                            "userteste@email.com",
                            "Comum"});
#line 83
    await testRunner.GivenAsync("que existe um usuário comum com os seguintes dados:", ((string)(null)), table19, "Dado ");
#line hidden
#line 86
    await testRunner.WhenAsync("eu tento promover o usuário a administrador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 87
    await testRunner.ThenAsync("a promoção deve ser bem-sucedida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 88
    await testRunner.AndAsync("as alterações devem ser persistidas no repositório", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 89
    await testRunner.AndAsync("o usuário atualizado deve ter o perfil \"Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PromoverUsuarioAAdministradorFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PromoverUsuarioAAdministradorFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
